name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Wasm Build
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
      run: |
        wasm-pack

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Node Build
      working-directory: ./www
      run: |
        npm install
        npm run build
